services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: prod
  #   restart: unless-stopped
  #   ports:
  #     - ${PORT}:${PORT}
  #   environment:
  #     APP_ENV: ${APP_ENV}
  #     PORT: ${PORT}
  #     BLUEPRINT_DB_HOST: ${BLUEPRINT_DB_HOST}
  #     BLUEPRINT_DB_PORT: ${BLUEPRINT_DB_PORT}
  #     BLUEPRINT_DB_DATABASE: ${BLUEPRINT_DB_DATABASE}
  #     BLUEPRINT_DB_USERNAME: root
  #     BLUEPRINT_DB_PASSWORD: Hncy@123qwe
  #     BLUEPRINT_DB_SCHEMA: ${BLUEPRINT_DB_SCHEMA}
  #   depends_on:
  #     psql_bp:
  #       condition: service_healthy
  #   networks:
  #     - blueprint
  psql_bp:
    image: registry.hncy.info/postgres:18.4-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_DB: sabertodo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Hncy@123qwe
    ports:
      - "5432:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U root -d sabertodo'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - blueprint

volumes:
  psql_volume_bp:
networks:
  blueprint:
