# Generated by Django 6.0.6 on 2026-06-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('NeedScore', models.IntegerField()),
                ('RewardEnergy', models.IntegerField()),
                ('RewardPetFood', models.IntegerField()),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('UpdateAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
